pipeline {
 environment {
        registry = 'jschuwan/api1'
        dockerHubCreds = 'docker_hub'
        dockerImage = ''
    }
    agent any
    stages {
        stage('Test') {
            when {
                branch 'feature/*'
            }
        steps {
            withMaven {
                cleanWs()
                sh 'mvn test'
            }
         }
       }

    stage('Docker Build') {
        when {
            branch 'main'
        }
        steps {
         dir('api1Reimb/') {
            script {
               docker exec -u 0 -it bash
               echo "$registry:$currentBuild.number"
               dockerImage = docker.build "$registry"
            }
         }
        }
    }
    stage('Docker Deliver') {
        when {
            branch 'main'
        }
        steps {
            script {
                docker.withRegistry('', dockerHubCreds) {
                    dockerImage.push("$currentBuild.number")
                    dockerImage.push("latest")
                }
            }
        }
     }
  }
}
